### ISSUE TITLE
Shutdown option does not shutdown computer.

### ISSUE THREAD

**Issue by Micxster** [Micxster/DotPass#1]
## The code that is intended to shutdown a user's computer
`:Shutdown
shutdown`

## How the issue is caused
As you can see in the attached video, I entered option 1, then option 3 (which is intended to shutdown a user's computer after they click the enter key), then a bunch of long code popped up and the program just closes itself.

## More details
We are currently working on a fix for this and by next release, it should be fixed. If not, please provide some source code that might help us get it done quicker. Once the issue is fixed, we will close it here.

**Thank you,**
Micah/TheTechGeekMicx

**Comment by TechGeekMic** [comment]
We are working on a fix. Expect this on v0.3.2.4.

**Comment by MX-Mic** [comment]
This issue was before official release, and when PasswordOffline was called "DotPass"
